version: '3.9'

services:
  template-validation-portal-service:
    build:
      context: '.'
      dockerfile: Dockerfile

    ports:
      - '6001:5000'   # host:container

    # REMOVE command completely (use Dockerfile CMD)
    # command: ...

    networks:
      - elevate_net

    env_file:
      - ./apiServices/src/main/.env

networks:
  elevate_net:
    external: false